import pandas as pd
import numpy as np

customers = pd.read_csv("data/customers.csv")
orders = pd.read_csv("data/orders.csv")
products = pd.read_csv("data/products.csv")
inventory = pd.read_csv("data/inventory.csv")
warehouses = pd.read_csv("data/warehouses.csv")
delivery = pd.read_csv("data/delivery_tracking.csv")
promotions = pd.read_csv("data/promotions.csv")
clickstream = pd.read_csv("data/clickstream.csv")
employee = pd.read_csv("data/employee_operations.csv")
website_clickstream = pd.read_csv("data/website_clickstream.csv")

print("Datasets Loaded Successfully")

print(customers.info())
print(orders.info())
print(products.info())
print(inventory.info())
print(warehouses.info())
print(delivery.info())
print(promotions.info())
print(clickstream.info())
print(employee.info())
print(website_clickstream.info())

customers["join_date"] = pd.to_datetime(customers["join_date"])
inventory["last_updated"] = pd.to_datetime(inventory["last_updated"])
promotions["start_date"] = pd.to_datetime(promotions["start_date"])
promotions["end_date"] = pd.to_datetime(promotions["end_date"])
clickstream["event_timestamp"] = pd.to_datetime(clickstream["event_timestamp"])
website_clickstream["event_timestamp"] = pd.to_datetime(website_clickstream["event_timestamp"])

print(customers.info())
print(inventory.info())
print(promotions.info())

print("Customers:", customers.duplicated().sum())
print("Orders:", orders.duplicated().sum())
print("Products:", products.duplicated().sum())
print("Inventory:", inventory.duplicated().sum())
print("Warehouses:", warehouses.duplicated().sum())
print("Delivery:", delivery.duplicated().sum())
print("Promotions:", promotions.duplicated().sum())
print("Clickstream:", clickstream.duplicated().sum())
print("Employee:", employee.duplicated().sum())
print("Website_Clickstream:", website_clickstream.duplicated().sum())

customers = customers.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
orders = orders.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
products = products.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
inventory = inventory.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
warehouses = warehouses.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
delivery = delivery.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
promotions = promotions.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
clickstream = clickstream.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
employee = employee.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
website_clickstream = website_clickstream.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

print("Quantity Min:", orders["quantity"].min())
print("Revenue Min:", orders["revenue"].min())
print("Price Min:", products["price"].min())
print("Stock Level Min:", inventory["stock_level"].min())
print("Discount Min:", promotions["discount_percentage"].min())
print("Discount Max:", promotions["discount_percentage"].max())
print("Estimated Days Min:", delivery["estimated_days"].min())

print(orders.info())
print(orders["order_timestamp"].head(10))

orders["order_timestamp"] = pd.to_datetime(
    orders["order_timestamp"]
)
print(orders.info())
print(clickstream.info())
delivery["actual_days"] = delivery["actual_days"].fillna(0)

print("Missing Values:")

print(customers.isnull().sum())
print(orders.isnull().sum())
print(products.isnull().sum())
print(inventory.isnull().sum())
print(warehouses.isnull().sum())
print(delivery.isnull().sum())
print(promotions.isnull().sum())
print(clickstream.isnull().sum())
print(website_clickstream.isnull().sum())
print(employee.isnull().sum())

customers.to_csv("cleaned_dataset/customers_clean.csv", index=False)
orders.to_csv("cleaned_dataset/orders_clean.csv", index=False)
products.to_csv("cleaned_dataset/products_clean.csv", index=False)
inventory.to_csv("cleaned_dataset/inventory_clean.csv", index=False)
warehouses.to_csv("cleaned_dataset/warehouses_clean.csv", index=False)
delivery.to_csv("cleaned_dataset/delivery_tracking_clean.csv", index=False)
promotions.to_csv("cleaned_dataset/promotions_clean.csv", index=False)
clickstream.to_csv("cleaned_dataset/clickstream_clean.csv", index=False)
website_clickstream.to_csv("cleaned_dataset/website_clickstream_clean.csv", index=False)

print("All cleaned datasets saved successfully!")